---
title: "Quick MR analysis of LDL on stroke"
author: "Gibran Hemani"
date: 2024-01-20
---

```{r}
library(dplyr)
library(here)
library(tidyr)
library(ggplot2)
```

Load in organised data

```{r}
out <- readRDS(here("data", "stroke_ldl", "organised_summary_data.rds"))
names(out)
metadata <- readRDS(here("data", "stroke_ldl", "metadata.rds"))
```

Reshape

```{r}
stroke_traits <- unique(metadata$trait)[-1]
dat <- lapply(1:length(out), \(i) {
    dat1 <- subset(out[[i]]$tophit_pool, target_trait == "LDL" & trait == "LDL")
    dat2 <- subset(out[[i]]$tophit_pool, target_trait == "LDL" & trait == stroke_traits[i])
    dat <- inner_join(dat1, dat2, by=c("vid", "pop"))
    dat
})
lapply(dat, head)
```

Run models

```{r}
res <- lapply(dat, \(d) {
    l <- list()
    l$mod1 <- lm(beta.y ~ -1 + beta.x, data=d, weight=1/d$se.y^2)
    l$mod2 <- lm(beta.y ~ -1 + beta.x:as.factor(pop), data=d, weight=1/d$se.y^2)
    l$smod1 <- summary(l$mod1)
    l$smod2 <- summary(l$mod2)
    l$modcomp <- anova(l$mod1, l$mod2)
    l
})
```

Reduced model combining all ancestries

```{r}
smod1
```

Per ancestry analysis

```{r}
smod2
```

Comparison of reduced and full model

```{r}
modcomp
```

Plot results

```{r}
ress <- lapply(1:length(stroke_traits), \(i) {
    smod2 <- res[[i]]$smod2
    as_tibble(smod2$coef) %>% mutate(pop = levels(as.factor(dat[[1]]$pop)), outcome=stroke_traits[i])
}) %>% bind_rows()

ress %>%
    ggplot(., aes(x=Estimate, y=pop)) +
    geom_point(aes(colour=pop)) +
    geom_errorbarh(aes(colour=pop, xmin=Estimate - `Std. Error` * 1.96, xmax=Estimate + `Std. Error` * 1.96), height=0) +
    geom_vline(xintercept=0, linetype="dotted") +
    scale_colour_brewer(type="qual", palette = 2) +
    facet_grid(outcome ~ .)
```


```{r}
ress %>%
    ggplot(., aes(x=Estimate, y=outcome)) +
    geom_point(aes(colour=pop)) +
    geom_errorbarh(aes(colour=pop, xmin=Estimate - `Std. Error` * 1.96, xmax=Estimate + `Std. Error` * 1.96), height=0) +
    geom_vline(xintercept=0, linetype="dotted") +
    scale_colour_brewer(type="qual", palette = 2) +
    facet_grid(pop ~ .)
```
