rule all:
    input:
        "quick_mr.html"

rule download_summary_data:
    input: "download_summary_data.r"
    output:
        "summary_metadata.rds"
    script:
        "download_summary_data.r"


rule download_ldref:
    output: "../../data/stroke_ldl/ref/AFR.bed"
    shell:
        """
        mkdir -p ../../data/stroke_ldl/ref
        cd ../../data/stroke_ldl/ref
        wget http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz
        tar xzvf 1kg.v3.tgz
        rm 1kg.v3.tgz
        """

rule recode_ref:
    input:
        "../../data/stroke_ldl/ref/AFR.bim"
    output:
        "../../data/stroke_ldl/ref/AFR_vid.bim"
    shell:
        """
        Rscript variant_ids.r ../../data/stroke_ldl/ref/AFR ../../data/stroke_ldl/ref/AFR_vid
        Rscript variant_ids.r ../../data/stroke_ldl/ref/EUR ../../data/stroke_ldl/ref/EUR_vid
        Rscript variant_ids.r ../../data/stroke_ldl/ref/EAS ../../data/stroke_ldl/ref/EAS_vid
        Rscript variant_ids.r ../../data/stroke_ldl/ref/SAS ../../data/stroke_ldl/ref/SAS_vid
        Rscript variant_ids.r ../../data/stroke_ldl/ref/AMR ../../data/stroke_ldl/ref/AMR_vid
        """

rule organise_summary_data:
    input:
        "../../data/stroke_ldl/summary_metadata.rds",
        "../../data/stroke_ldl/ref/AFR_vid.bim"
    output:
        "../../data/stroke_ldl/organised_summary_data.rds"
    script:
        "organise_summary_data.r"

rule quick_mr:
    input:
        "../../data/stroke_ldl/organised_summary_data.rds",
        "quick_mr.rmd"
    output:
        "quick_mr.html"
    script:
        "quick_mr.rmd"

rule create_dummy_data:
    input: "../../data/stroke_ldl/organised_summary_data.rds"
    output:
        "dummy_data.rds"
    script:
        "create_dummy_data.r"

rule mr:
    input: "../../data/stroke_ldl/organised_summary_data.rds"
    output:
        "mr.html"
    script:
        "mr.rmd"
