---
title: Instrument specificity simulation results analysis
---

```{r}
library(tidyverse)
library(here)
load(here("results", "instrument_specificity.rdata"))

# Pull back parameters that were omitted frmo output in oinst
temp <- subset(omr, !duplicated(simid), select=c(simid, lddir1, lddir2, region, nid1, nid2, removecv, pshared, pdistinct, p1, nsim, hsq1, window, sim, bxy1, bxy2, mc.cores))
temp2 <- subset(oinst, select=c("simid", names(oinst)[!names(oinst) %in% names(temp)]))
oinst <- inner_join(temp2, temp, by="simid")

o1s <- oinst %>% group_by(nid2, lddir2, method, removecv, pshared) %>%
  summarise(
    n=n(),
    prop_same=mean(prop_same),
    auc=mean(auc),
    correct_sig=mean(correct_sig),
    obs_rep=mean(obs_rep),
    exp_rep=mean(exp_rep),
    binom_p=mean(-log10(binom_p)),
    fdr=mean(fdr),
    pow=mean(pow)
  ) %>% ungroup %>% 
  mutate(
    lddir2=basename(as.character(lddir2)), 
    cv=case_when(pshared == 0 ~ "Distinct CV", TRUE ~ "Shared CV"),
    lddir2=gsub("ld", "EUR - ", lddir2)
  )
```



```{r}
ggplot(o1s, aes(x=nid2, y=auc)) +
geom_point(aes(colour=method, shape=removecv)) +
geom_line(aes(colour=method, linetype=removecv)) +
facet_grid(lddir2 ~ cv)
```

```{r}
ggplot(o1s, aes(x=nid2, y=binom_p)) +
geom_point(aes(colour=method, shape=removecv)) +
geom_line(aes(colour=method, linetype=removecv)) +
facet_grid(lddir2 ~ cv)
```

```{r}
o1s %>% 
  group_by(nid2, removecv, method) %>%
  summarise(fdr=mean(fdr)) %>%
  ggplot(., aes(x=nid2, y=fdr)) +
  geom_point(aes(colour=method, shape=removecv)) +
  geom_line(aes(colour=method, linetype=removecv))
```

```{r}
ggplot(o1s, aes(x=nid2, y=pow)) +
geom_point(aes(colour=method, shape=removecv)) +
geom_line(aes(colour=method, linetype=removecv)) +
facet_grid(lddir2 ~ cv)
```

```{r}
ggplot(o1s, aes(x=nid2, y=prop_same)) +
geom_point(aes(colour=cv, shape=removecv)) +
geom_line(aes(colour=cv, linetype=removecv)) +
facet_grid(lddir2 ~ .)
```

