# Need to get list of wildcards before running. Slightly annoying. Run
# Rscript gwashits.r
# before starting

import json
import pandas as pd
with open('config.json', 'r') as f:
  config = json.load(f)

datadir = config['ld_data_dir']
outdir = config['outdir']
region = pd.read_csv("data/region.txt", header=None, sep=" ")
regions = list(region[3])


rule all:
    input:
        expand("{outdir}/results2.rdata", outdir=outdir)

rule download_ld_ref:
    output:
        "EUR.rdata"
    shell:
        """
        wget http://fileserve.mrcieu.ac.uk/ld/1kg.v3.tgz
        mv 1kg.v3.tgz {datadir}
        cd {datadir}
        tar xzvf 1kg.v3.tgz
        rm 1kg.v3.tgz
        """

rule whole_genome_ld_loss:
    input:
        "data/gwashits.rdata",
        "whole_genome_ld_loss.r",
        expand("{datadir}/EUR.bed", datadir=datadir)
    output:
        "{outdir}/{regions}/result2.rdata"
    shell:
        "Rscript whole_genome_ld_loss.r {wildcards.regions}"

rule aggregate:
    input:
        expand("{outdir}/{regions}/result2.rdata", outdir=outdir, regions=regions)
    output:
        "{outdir}/results2.rdata"
    script:
        "aggregate.r"
