---
title: Simulating across various scenarios
---

## Background

- Scenario 1: Use EUR discovery bgx for all ancestries
- Scenario 2: Use EUR discovery SNP, re-estimate bgx in all ancestries
- Scenario 3: Use meta analysis bgx to discovery SNP, re-estimate in all ancestries



```{r}
library(simulateGP)
library(dplyr)
library(data.table)
library(here)
library(TwoSampleMR)
library(furrr)
library(parallel)
```



```{r}
organise_ldobj <- function(dirs, region)
{
  ld <- lapply(dirs, \(x) readRDS(file.path(x, paste0("ldobj_", region, ".rds"))))
  x1 <- unique(ld[[1]]$map$snp)
  x <- Reduce(intersect, lapply(ld, \(x) x$map$snp))[1:500]
  ld <- lapply(ld, \(y) subset_ldobj(y, x))
  names(ld) <- gsub("ld", "", basename(dirs))
  stopifnot(all(ld[[1]]$map$snp == ld[[2]]$map$snp))
  return(ld)
}


subset_ldobj <- function(ldobj, snps)
{
  i <- which(ldobj$map$snp %in% snps)
  ldobj$map <- ldobj$map[i,]
  ldobj$ld <- ldobj$ld[i,i]
  return(ldobj)
}

dirs <- here("data", "ld", c("ldAFR", "ldAMR", "ldEAS", "ldEUR", "ldSAS"))
region <- "1_83991748_84844495"
ld <- organise_ldobj(dirs, region)
str(ld)
```

```{r}
regions <- c("12_106958748_109025901", "14_101534307_103012102", "1_83991748_84844495", "2_14335308_16329735", "5_110821144_111981562", "5_140645971_142981248", "6_134244243_136224177", "6_151912703_153094496", "6_42038721_43756169", "7_135591083_136876562")

ld_objs <- lapply(regions, organise_ldobj, dirs=dirs)
names(ld_objs) <- regions
```

```{r}
ld_fast <- function(params, nid, ld, minmaf=0.01) {
    xvar <- sqrt(2 * params[["af"]] * (1-params[["af"]]))
    params %>%
        dplyr::mutate(
            af = pmax(minmaf, af) %>% pmin(1-minmaf, 1-af),
            beta_ld = (diag(1/xvar) %*% ld %*% diag(xvar) %*% beta) %>% drop(),
            se = expected_se(beta_ld, af, nid, vy=1),
            bhat = stats::rnorm(length(beta_ld), beta_ld, se),
            fval = (bhat / se)^2,
            n = nid,
            pval = pf(fval, df1=1, df2=nid-1, lower.tail=FALSE)
        )
}


# ax1 <- ld[["EUR"]]$map %>%
#         generate_gwas_params(h2=0.001, S=0, Pi=1/nrow(.)) 

# microbenchmark(ax <- ax1 %>%
#         ld_fast(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld), times=1)

# library(microbenchmark)
# microbenchmark(ax2 <- ax1 %>%
#         generate_gwas_ss(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld), times=1)

# microbenchmark(ax3 <- ax1 %>%
#         generate_gwas_ss(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld), times=1)

# head(ax)
# head(ax2)

# var(ax$bhat)
# var(ax2$bhat)

# cor(ax$bhat, ax2$bhat)
# cor(ax3$bhat, ax2$bhat)
# lm(ax$bhat ~ ax2$bhat)

# pdf()
# plot(ax$bhat, ax2$bhat)
```

```{r}
simss_fast <- function(ld, nid, bxy, h2=0.05) {
    ax <- ld[["EUR"]]$map %>%
        generate_gwas_params(h2=h2, S=0, Pi=1/nrow(.)) %>%
        ld_fast(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld)
    ay <- ax %>% select(chr, snp, pos, alt, ref, af, beta) %>% mutate(beta=beta*bxy[["EUR"]]) %>%
        ld_fast(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld)
    a <- merge(ax, ay, by=c("chr", "snp", "pos", "alt", "ref", "af"))

    pops <- names(ld)[!names(ld) %in% "EUR"]

    b <- lapply(pops, \(pop) {
        bx <- ld[[pop]]$map %>%
            mutate(beta=ax$beta) %>%
            ld_fast(nid=nid[[pop]], ld=ld[[pop]]$ld)
        by <- bx %>% select(chr, snp, pos, alt, ref, af, beta) %>% mutate(beta=beta*bxy[[pop]]) %>%
            ld_fast(nid=nid[[pop]], ld=ld[[pop]]$ld)
        b <- merge(bx, by, by=c("chr", "snp", "pos", "alt", "ref", "af"))
    })
    names(b) <- pops
    return(list(a=a, b=b))

}
```


```{r}

simss <- function(ld, nid, bxy, h2=0.05) {
    ax <- ld[["EUR"]]$map %>%
        generate_gwas_params(h2=h2, S=0, Pi=1/nrow(.)) %>%
        generate_gwas_ss(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld)
    ay <- ax %>% select(chr, snp, pos, alt, ref, af, beta) %>% mutate(beta=beta*bxy[["EUR"]]) %>%
        generate_gwas_ss(nid=nid[["EUR"]], ld=ld[["EUR"]]$ld)
    a <- merge(ax, ay, by=c("chr", "snp", "pos", "alt", "ref", "af"))

    pops <- names(ld)[!names(ld) %in% "EUR"]

    b <- lapply(pops, \(pop) {
        bx <- ld[[pop]]$map %>%
            mutate(beta=ax$beta) %>%
            generate_gwas_ss(nid=nid[[pop]], ld=ld[[pop]]$ld)
        by <- bx %>% select(chr, snp, pos, alt, ref, af, beta) %>% mutate(beta=beta*bxy[[pop]]) %>%
            generate_gwas_ss(nid=nid[[pop]], ld=ld[[pop]]$ld)
        b <- merge(bx, by, by=c("chr", "snp", "pos", "alt", "ref", "af"))
    })
    names(b) <- pops
    return(list(a=a, b=b))
}
```

```{r}
fixed_effects_meta_analysis <- function(beta_vec, se_vec, infl=10000) {
    ind <- identify_blownup_estimates(beta_vec, se_vec, infl)
    beta_vec[ind] <- NA
    se_vec[ind] <- NA
    w <- 1 / se_vec^2
    beta <- sum(beta_vec * w, na.rm=T) / sum(w, na.rm=T)
    se <- sqrt(1 / sum(w, na.rm=T))
    pval <- pnorm(abs(beta / se), lower.tail = FALSE)
    Qj <- w * (beta-beta_vec)^2
    Q <- sum(Qj, na.rm=T)
    Qdf <- sum(!is.na(beta_vec))-1
    if(Qdf == 0) Q <- 0
    Qjpval <- pchisq(Qj, 1, lower.tail=FALSE)
    Qpval <- pchisq(Q, Qdf, lower.tail=FALSE)
    return(list(beta=beta, se=se, pval=pval, Q=Q, Qdf=Qdf, Qpval=Qpval, Qj=Qj, Qjpval=Qjpval))
}

identify_blownup_estimates <- function(b, se, infl) {
  semin <- which.min(se)
  abs(b) > infl*abs(b[semin])
}

fixed_effects_meta_analysis_fast <- function(beta_mat, se_mat) {
  w <- 1 / se_mat^2
  beta <- rowSums(beta_mat * w) / rowSums(w, na.rm=TRUE)
  se <- sqrt(1 / rowSums(w, na.rm=TRUE))
  z <- abs(beta / se)
  p <- pnorm(z, lower.tail = FALSE)
  nstudy <- apply(beta_mat, 1, \(x) sum(!is.na(x)))
  return(tibble(nstudy, p, z=z))
}

scenario1 <- function(a, b) {
    as <- a[which.min(a$pval.x),]
    mra <- mr_wald_ratio(as$bhat.x, as$bhat.y, as$se.x, as$se.y) %>% as_tibble() %>%
        mutate(pop="EUR", fstat=as$fval.x, cv=as$beta.x!=0)
        

    mrb <- lapply(names(b), \(pop) {
        bs <- subset(b[[pop]], snp == as$snp)
        mrb <- mr_wald_ratio(as$bhat.x, bs$bhat.y, as$se.x, bs$se.y) %>% as_tibble() %>%
            mutate(pop=pop, fstat=bs$fval.x, cv=bs$beta.x!=0)
        return(mrb)
    }) %>% bind_rows()


    res <- bind_rows(mra, mrb)
    q <- fixed_effects_meta_analysis(res$b, res$se)
    res$Qjpval <- q$Qjpval
    bind_rows(res, tibble(b=q$beta, se=q$se, pval=q$pval, pop="All", nsnp=1, Qjpval=q$Qpval)) %>%
        mutate(scanerio=1)
}

scenario2 <- function(a, b) {
    as <- a[which.min(a$pval.x),]
    mra <- mr_wald_ratio(as$bhat.x, as$bhat.y, as$se.x, as$se.y) %>% as_tibble() %>%
        mutate(pop="EUR", fstat=as$fval.x, cv=as$beta.x!=0)
        

    mrb <- lapply(names(b), \(pop) {
        bs <- subset(b[[pop]], snp == as$snp)
        mrb <- mr_wald_ratio(bs$bhat.x, bs$bhat.y, bs$se.x, bs$se.y) %>% as_tibble() %>%
            mutate(pop=pop, fstat=bs$fval.x, cv=bs$beta.x!=0)
        return(mrb)
    }) %>% bind_rows()


    res <- bind_rows(mra, mrb)
    q <- fixed_effects_meta_analysis(res$b, res$se)
    res$Qjpval <- q$Qjpval
    bind_rows(res, tibble(b=q$beta, se=q$se, pval=q$pval, pop="All", nsnp=1, Qjpval=q$Qpval)) %>%
        mutate(scanerio=2)
}


scenario3 <- function(a, b) {
    bmat <- cbind(a$bhat.x, lapply(b, \(x) x$bhat.x) %>% do.call(cbind, .))
    semat <- cbind(a$se.x, lapply(b, \(x) x$se.x) %>% do.call(cbind, .))
    fema <- fixed_effects_meta_analysis_fast(bmat, semat)
    which.min(fema$p)
    which.min(a$pval.x)
    snp <- which.min(fema$p)
    as <- a[snp,]
    mra <- mr_wald_ratio(as$bhat.x, as$bhat.y, as$se.x, as$se.y) %>% as_tibble() %>%
        mutate(pop="EUR", fstat=as$fval.x, cv=as$beta.x!=0)
        

    mrb <- lapply(names(b), \(pop) {
        bs <- subset(b[[pop]], snp == as$snp)
        mrb <- mr_wald_ratio(bs$bhat.x, bs$bhat.y, bs$se.x, bs$se.y) %>% as_tibble() %>%
            mutate(pop=pop, fstat=bs$fval.x, cv=bs$beta.x!=0)
        return(mrb)
    }) %>% bind_rows()


    res <- bind_rows(mra, mrb)
    q <- fixed_effects_meta_analysis(res$b, res$se)
    res$Qjpval <- q$Qjpval
    bind_rows(res, tibble(b=q$beta, se=q$se, pval=q$pval, pop="All", nsnp=1, Qjpval=q$Qpval)) %>%
        mutate(scanerio=3)
}
```

```{r}
nid <- list(EUR=1000000, AFR=100000, AMR=100000, EAS=100000, SAS=100000)
bxy <- list(EUR=0.3, AFR=0.3, AMR=0.3, EAS=0.3, SAS=0.3)
o3 <- simss_fast(ld, nid, bxy)
scenario1(o3$a, o3$b)
scenario2(o3$a, o3$b)
scenario3(o3$a, o3$b)

bxy <- list(EUR=0.3, AFR=0.3, AMR=0.3, EAS=0.3, SAS=-0.3)
o3h <- simss_fast(ld, nid, bxy)


scenario1(o3h$a, o3h$b)
scenario2(o3h$a, o3h$b)
scenario3(o3h$a, o3h$b)
```


```{r}
sim <- function(neur, nmult, bxy, bhet, region, h2=0.05, nsim=1) {
  args <- as.list(environment()) %>% as_tibble()
  dirs <- here("data", "ld", c("ldAFR", "ldAMR", "ldEAS", "ldEUR", "ldSAS"))
  ld <- ld_objs[[region]]
  nid <- list(EUR=neur, AFR=neur*nmult, AMR=neur*nmult, EAS=neur*nmult, SAS=neur*nmult)
  bxy <- as.list(rnorm(length(nid), bxy, bhet))
  names(bxy) <- names(nid)
  o <- simss(ld, nid, bxy, h2)
  r <- bind_rows(
    scenario1(o$a, o$b),
    scenario2(o$a, o$b),
    scenario3(o$a, o$b)
  ) %>% bind_cols(args)
  bxy <- data.frame(pop=names(bxy), true_bxy=unlist(bxy))
  r <- left_join(r, bxy, by="pop")
}

res <- sim(100000, 0.7, 0.2, 0.3, "1_83991748_84844495")
res %>% str
```


```{r}
param <- expand.grid(
  neur=c(100000, 1000000),
  nmult=c(0.1, 1),
  bxy=c(0.2),
  bhet=c(rep(0, 5), seq(0.05, 0.3, by=0.05)),
  region=regions[1:5],
  nsim=1:10
)
dim(param)
res <- do.call(sim, param[1,])
res
```


```{r}
res <- purrr::pmap(param, sim, .progress=TRUE) %>% bind_rows()
saveRDS(res, here("results", "scenario_simulations_a.rds"))
```


```{r}
param <- expand.grid(
  neur=c(10000, 100000, 1000000),
  nmult=c(0.1, 1),
  bxy=c(0.2, 0),
  bhet=c(rep(0, 1), seq(0.05, 0.3, by=0.05)),
  h2=c(0.001, 0.01),
  region=regions[1:5],
  nsim=1:100
)
dim(param)
```


```{r}
res <- purrr::pmap(param, sim, .progress=TRUE) %>% bind_rows()
saveRDS(res, here("results", "scenario_simulations2_b.rds"))
```


## Analysis

```{r}
library(ggplot2)
res <- bind_rows(
    readRDS(here("results", "scenario_simulations.rds")),
    readRDS(here("results", "scenario_simulations2.rds"))
)

res <- readRDS(here("results", "scenario_simulations2_b.rds"))

res$h2[is.na(res$h2)] <- 0.05
p1 <- res %>% filter(pop=="All") %>% group_by(scanerio, neur, nmult, h2, bhet) %>% summarise(het=sum(Qjpval < 0.05)/n(), n=n()) %>%
    ggplot(aes(y=het, x=bhet, color=factor(scanerio))) + geom_line() + facet_wrap(~nmult*h2+neur, labeller=label_both) + scale_colour_brewer(type="qual")
ggsave(p1, file="p1.png")
```


FDR

```{r}
p1 <- res %>% filter(bhet == 0) %>% group_by(scanerio, neur, nmult, h2, pop) %>% summarise(het=mean(Qjpval < 0.05,na.rm=T), n=n()) %>%
    ggplot(aes(y=het, x=neur, color=factor(pop))) + geom_line() + facet_grid(scanerio~nmult*h2, labeller=label_both) + scale_colour_brewer(type="qual") +
    geom_hline(yintercept=0.05, linetype="dotted")
ggsave(p1, file="p1fdr.png")
```



```{r}
p1 <- res %>% filter(pop=="All" & bxy == 0.2) %>% group_by(scanerio, neur, nmult, h2, bxy, bhet) %>% summarise(mse=mean((b-bxy)^2), n=n()) %>%
    ggplot(aes(y=mse, x=bhet, color=factor(scanerio))) + geom_line() + facet_wrap(~nmult+h2+neur, labeller=label_both) + scale_colour_brewer(type="qual")
ggsave(p1, file="p2.png")
```


```{r}
p1 <- res %>% filter(pop=="All") %>% group_by(scanerio, neur, nmult, h2, bxy, bhet) %>% summarise(pow=mean(pval < 0.05), n=n()) %>%
    ggplot(aes(y=pow, x=bhet, color=factor(scanerio))) + geom_line(aes(linetype=as.factor(bxy))) + facet_wrap(~nmult+h2+neur, labeller=label_both) + scale_colour_brewer(type="qual")
ggsave(p1, file="p3.png")
```


```{r}
p1 <- res %>% filter(bxy==0 & nmult == 1 & pop != "All") %>% group_by(scanerio, neur, nmult, h2, pop, bhet) %>% summarise(pow=mean(pval < 0.05), n=n()) %>%
    ggplot(aes(y=pow, x=bhet, color=factor(pop))) + geom_line() + facet_grid(scanerio~nmult+h2+neur, labeller=label_both) + scale_colour_brewer(type="qual")
ggsave(p1, file="p3pop.png")
```


```{r}
p1 <- res %>% filter(pop=="All") %>% group_by(scanerio, neur, nmult, h2, bxy, bhet) %>% summarise(pow=mean(-log10(pval)), n=n()) %>%
    ggplot(aes(y=pow, x=bhet, color=factor(scanerio))) + geom_line() + facet_wrap(~nmult+h2+neur, labeller=label_both) + scale_colour_brewer(type="qual")
ggsave(p1, file="p4.png")
```


```{r}
p1 <- res %>% filter(pop!="All") %>% group_by(pop, scanerio, neur, nmult, h2, bxy, bhet) %>% summarise(mse=mean((b-true_bxy)^2), n=n()) %>%
    ggplot(aes(y=mse, x=bhet, color=factor(scanerio))) + geom_line() + facet_grid(pop~nmult+h2+neur, labeller=label_both) + scale_colour_brewer(type="qual") +
    ylim(0, 1)
ggsave(p1, file="p5.png")
```

```{r}
p1 <- res %>% filter(pop!="All") %>% group_by(pop, scanerio, neur, nmult, h2, bxy, bhet) %>% summarise(pow=mean(pval < 0.05), n=n()) %>%
    ggplot(aes(y=pow, x=bhet, color=factor(scanerio))) + geom_line() + facet_grid(pop+nmult~h2+neur) + scale_colour_brewer(type="qual") +
    ylim(0, 1)
ggsave(p1, file="p6.png")
```


## More sample sizes

```{r}
param <- expand.grid(
  neur=seq(100000, 1000000, by=100000),
  nmult=c(0.1, 1),
  bxy=c(0.2),
  bhet=0,
  h2=c(0.01),
  region=regions[1:5],
  nsim=101:500
)
dim(param)
```


```{r}
res <- purrr::pmap(param, sim, .progress=TRUE) %>% bind_rows()
saveRDS(res, here("results", "scenario_simulations2_d.rds"))
```



```{r}
res <- readRDS(here("results", "scenario_simulations2_c.rds"))
```


```{r}
p1 <- res %>% filter(bhet == 0) %>% group_by(scanerio, neur, nmult, h2, pop) %>% summarise(het=mean(Qjpval < 0.05,na.rm=T), n=n()) %>%
    ggplot(aes(y=het, x=neur, color=factor(pop))) + geom_line() + facet_grid(scanerio~nmult*h2, labeller=label_both) + scale_colour_brewer(type="qual") +
    geom_hline(yintercept=0.05, linetype="dotted")
ggsave(p1, file="p1fdr.png")
```
